Fix the added document addresses and modified text styles
goodrain/rainbond-ui pull request #692
Opened 2021-04-29 07:58 UTC by henwasaia

added document addresses and modified text styles

2021-04-29 08:21 UTC, henwasaia commented
To solve the problem ：Added document address and removed rainbond related identifier
solution ：write code
test results : Added document addresses and completed the replacement of RainBond related characters

2021-04-29 12:36 UTC, barnettZQG requested changes

2021-04-29 12:36 UTC, barnettZQG commented on src/components/OuterCustomForm/index.js
> +                      (platform_url && (
You should click on the icon to jump. Tooltip is just a reminder.

2021-04-29 12:36 UTC, barnettZQG commented on src/components/OuterCustomForm/index.js
> +                          (platform_url && (
You should click on the icon to jump. Tooltip is just a reminder.

2021-04-29 12:36 UTC, barnettZQG commented on src/pages/AddCluster/index.js
>                  <Col span={8}>
The scan module should not be shown in the enterprise version.

2021-04-29 12:36 UTC, barnettZQG commented on src/pages/Component/expansion.js
> +                        查询详细的组件实例信息，请复制查询命令到平台管理节点查询
"请复制查询命令到平台管理节点查询" > "请复制查询命令到集群管理节点查询"

2021-04-29 12:36 UTC, barnettZQG commented on src/pages/Component/index.js
> -        <ManageAppGuide />
Why is this module deleted?

2021-04-29 12:36 UTC, barnettZQG commented on src/pages/Component/setting/auto-deploy.js
> +                      (platform_url && (
Same as above.

2021-04-29 12:36 UTC, barnettZQG commented on src/pages/Component/setting/auto-deploy.js
> +                      (platform_url && (
Same as above.

2021-04-29 12:36 UTC, barnettZQG commented on src/pages/EnterpriseShared/AppExporter.js
> +        title="平台App规范(平台可用)"
平台App规范(平台可用) =》 应用模型规范

2021-04-29 12:36 UTC, barnettZQG commented on src/pages/EnterpriseShared/Details.js
> +          content="应用模型是指模型化、标准化的应用制品包，是企业数字资产的应用化产物，可以通过标准的方式安装到任何平台或其他支持的云原生平台"
修改为：“应用市场支持Rainstore应用商店和Helm应用商店的对接和管理”

2021-04-29 12:36 UTC, barnettZQG commented on src/pages/EnterpriseShared/index.js
> +        content="应用模型是指模型化、标准化的应用制品包，是企业数字资产的应用化产物，可以通过标准的方式安装到任何平台或其他支持的云原生平台"
Same as above.

2021-04-29 12:36 UTC, barnettZQG commented on src/pages/User/registerComponent.js
> +              请注意：注册使用即同意平台发行版用户许可协议。
注册使用即同意产品发行版用户许可协议。

2021-04-29 12:36 UTC, barnettZQG commented
PR to the master branch.

2021-04-30 07:42 UTC, barnettZQG requested changes

2021-04-30 07:42 UTC, barnettZQG commented on config/config.js
> +      target: 'http://4000.gr7c60a0.2c9v614j.17f4cc.grapps.cn',
Custom configurations do not commit.

2021-04-30 07:42 UTC, barnettZQG commented on src/pages/AddCluster/index.js
> +                {/* 企业版的不需要显示扫描模块 */}
下面的文字也需要包括在控制域里面啊。

2021-04-30 08:19 UTC, barnettZQG approved these changes

2021-05-01 02:04 UTC, merged